version: '3'
services:
    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=postgres
    server:
        build: ./server
        command: ./gin-bin
        depends_on:
            - "postgres"
        environment:
            - POSTGRES_PASSWORD=postgres
    nginx:
        build: ./nginx
        ports: 
            - "8000:80"
